FROM python:3.11-slim

USER root
RUN apt-get update && apt-get install -y gcc python3-dev

RUN pip3 install fastapi sqlalchemy psycopg2-binary uvicorn boto3 redis

COPY src src

WORKDIR /src

EXPOSE 8000

CMD ["uvicorn" , "main:app" , "--reload", "--host", "0.0.0.0", "--port", "8000"]