apiVersion: v1
kind: Pod
metadata:
  name: redis-client
spec:
  containers:
  - name: redis
    image: redis:latest
    env:
    - name: REDIS_HOST
      value: "my-redis-cluster.wahhz8.0001.use1.cache.amazonaws.com"
    - name: REDIS_PORT
      value: "6379"